### ISSUE TITLE
please version and tag this project

### ISSUE THREAD

**Issue by aviau** [collectd/go-collectd#16]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for go-collectd and versioning would help Debian keep up with development.

**Comment by tokkee** [comment]
Are there any specific requirements or recommended best practices around versioning Go libraries (in Debian)? In particular, since there's nothing like a SONAME version in Go, how are build dependencies handled usually? gopkg.in kinda suggests using the major version for a similar purpose. Is that all you'd care about?

**Comment by aviau** [comment]
Tagging the repository and respecting http://semver.org/ is all I care about.

We don't yet ship golang .so in Debian but even when we do that is going to be our job to version them.

**Comment by octo** [comment]
I've just pushed tag "v0.1.0".

Best regards,
—octo
