### ISSUE TITLE
Setting the the size of the operating system's receive buffer

### ISSUE THREAD

**Issue by hasso** [collectd/go-collectd#22]
Default size of the receive buffer OSes are assigning to connections isn't often big enough for receiving a lot of traffic and it needs to be adjusted. There isn't a way to do it at the moment from application using go-collectd and I have to patch go-collectd itself - it shouldn't be necessary.

**Comment by octo** [comment]
Hi @hasso, thanks for reporting this.

I don't think proxying all sorts of UDP settings through the *network* API is the right way to go. What do you think about this approach:

*   Add `Conn *net.UDPConn` to the `Server` type.
*   If `Conn == nil`, use `Addr` to create a new `*net.UDPConn` with default settings.
*   Otherwise, use the user-provided `Conn`.

Best regards,
—octo

**Comment by octo** [comment]
That should fix this.. If this doesn't work for your case, let me know!
