### ISSUE TITLE
type *tar.Header has no field or method PAXRecords

### ISSUE THREAD

**Issue by nicolasStevenin** [collectd/go-collectd#36]
Hi, 

When I try to test archive, diff/walking and services/tasks, they faileds with

```
+ go test -compiler gc -ldflags ' -extldflags '\''-Wl,-z,relro  '\'''
Testing archive…
~/build/BUILD/containerd-1.0.1/_build/src/github.com/containerd/containerd/archive ~/build/BUILD/containerd-1.0.1
# github.com/containerd/containerd/archive
./tar.go:406:10: hdr.PAXRecords undefined (type *"github.com/dmcgowan/go-tar".Header has no field or method PAXRecords)
./tar.go:407:8: hdr.PAXRecords undefined (type *"github.com/dmcgowan/go-tar".Header has no field or method PAXRecords)
./tar.go:409:7: hdr.PAXRecords undefined (type *"github.com/dmcgowan/go-tar".Header has no field or method PAXRecords)
./tar.go:535:29: hdr.PAXRecords undefined (type *"github.com/dmcgowan/go-tar".Header has no field or method PAXRecords)
FAIL    github.com/containerd/containerd/archive [build failed]
```

Thank you for your help

**Comment by justinclift** [comment]
As a data point for anyone else that hits this, it's probably due to the version of Go being used.

On a system here with Go 1.9.x, this error occurs.  After manually upgrading to a new Go version (1.11beta2) the error no longer happens.

As a rough guess, it'll probably work with Go 1.10.x too, though I haven't tried that personally and mostly likely won't. :smile:

**Comment by octo** [comment]
Hi Stevenin and Justin,

this sounds like an incompatibility between the `github.com/containerd/containerd/archive` package and the `github.com/dmcgowan/go-tar` package. As far as I'm aware, this repository uses neither package. I'm not quite sure how this issue ended up here, but I don't think I can address this.

Best regards,
—octo
